name: CI Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  issues:
    types: [opened]
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.1.1
      - name: Awesome Github script action
        uses: actions/github-script@v6
        with:
          script: |
            var whoToGreet = core.getInput('who-to-greet');
            core.notice('Cześć ${whoToGreet}');
            core.setOutput('answer', 42);
            if (context.eventName === 'issues') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Thanks for reporting!'
              })
            }
      - name: Output the answer (wypisz odpowiedź)
        run: echo "Odpowiedź to ${{ steps.my-action.outputs.answer }}"
