name: CI Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  issues:
    types: [opened]
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.1.1
      - name: Run my own composite action (uruchom moją własną akcję złożoną)
        id: my-action
        uses: ./
        with:
          who-to-greet: "@wulfland"
      - name: Output the answer (wypisz odpowiedź)
        run: echo "Odpowiedź to ${{ steps.my-action.outputs.answer }}"
